{% set version = "1.0-24" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spray/spray_{{ version }}.tar.gz
  sha256: 734e6f03b84ced14fdf99c0ecf4c440e21fcf94e485f75f4412ea7869c5a1330

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-disordr >=0.0_8
    - r-magic
    - r-mathjaxr
    - r-partitions
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-disordr >=0.0_8
    - r-magic
    - r-mathjaxr
    - r-partitions

test:
  commands:
    - $R -e "library('spray')"           # [not win]
    - "\"%R%\" -e \"library('spray')\""  # [win]

about:
  home: https://github.com/RobinHankin/spray.git
  license: GPL-2.0-or-later
  summary: Sparse arrays interpreted as multivariate polynomials.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj

# Package: spray
# Type: Package
# Title: Sparse Arrays and Multivariate Polynomials
# Version: 1.0-7
# Authors@R: person(given=c("Robin", "K. S."), family="Hankin", role = c("aut","cre"), email="hankin.robin@gmail.com", comment = c(ORCID = "0000-0001-5982-0415"))
# Maintainer: Robin K. S. Hankin <hankin.robin@gmail.com>
# Description: Sparse arrays interpreted as multivariate polynomials.
# License: GPL (>= 2)
# Depends: methods
# Suggests: polynom
# Imports: Rcpp (>= 0.12.3),partitions,magic
# LinkingTo: Rcpp
# SystemRequirements: C++11
# URL: https://github.com/RobinHankin/spray.git
# BugReports: https://github.com/RobinHankin/spray/issues
# NeedsCompilation: yes
# Packaged: 2019-09-02 01:12:41 UTC; rhankin
# Author: Robin K. S. Hankin [aut, cre] (<https://orcid.org/0000-0001-5982-0415>)
# Repository: CRAN
# Date/Publication: 2019-09-02 22:30:02 UTC
