{% set version = "1.0-24" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spray/spray_{{ version }}.tar.gz
  sha256: 734e6f03b84ced14fdf99c0ecf4c440e21fcf94e485f75f4412ea7869c5a1330

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-disordr >=0.9_6
    - r-magic
    - r-mathjaxr
    - r-partitions
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-disordr >=0.9_6
    - r-magic
    - r-mathjaxr
    - r-partitions

test:
  commands:
    - $R -e "library('spray')"           # [not win]
    - "\"%R%\" -e \"library('spray')\""  # [win]

about:
  home: https://github.com/RobinHankin/spray.git
  license: GPL-2.0-or-later
  summary: Sparse arrays interpreted as multivariate polynomials.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
