{% set version = "1.0-27" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spray/spray_{{ version }}.tar.gz
  sha256: 7a23316d904d0ee37feb066121b5eb48c500aeceb76af1fac143ff2779fd0025

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-disordr >=0.9_6
    - r-magic
    - r-partitions
    - r-stringr
  run:
    - r-base
    - r-rcpp >=0.12.3
    - r-disordr >=0.9_6
    - r-magic
    - r-partitions
    - r-stringr

test:
  commands:
    - $R -e "library('spray')"           # [not win]
    - "\"%R%\" -e \"library('spray')\""  # [win]

about:
  home: https://github.com/RobinHankin/spray
  license: GPL-2.0-or-later
  summary: Sparse arrays interpreted as multivariate polynomials.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
