appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IaQWNBr61e4+JRoLPymz/WL0PR68LVQrrIGlaDug9iJ014tun60BiuGWiIoO+OlemulDehKAeFk7bEMCznJejrrWcEBOjiJvOgnwXH3O6/nhDGRqPAj1EHu/OQhlEyDk4z5AYf5nN5bmAnfwmwVm0U+I92KzgzQQQRl6gfwIzJCb5JBAqkaEZHdP0fTZA6YIzPc47zlgVESnUfcT/O7ixnG4HRYUooCn7rzoNjzS2UKgb9F5YNb1tv4/bBsbyoyG6WGlmv/PbCFZM298DfwmrVprxRMllPkzurnAriWqKoq3CMK4VYT2Vkl0J2xUA3TkQh3D/p650zafHuwZ9dfjUbG7kg4YYvApACtgWiMowUI/guUx5UCLlYesSfdOfnhURUUgK1hVFk2hPR5JWrRT1ASANa/3D1T+JzDseUOdz6wbuV2s1xwew/zOEKxla4LTwS+OvHxlpJkPST5WXgsqgIrs2/E9WONQxlUQsKU0BsSFLdY7raS++Porri/hbTFzyULuygh6ryqIO2ORTUTtUK4uQZSpucg3EC+QqN+914Qpp+ki3Y0/B24GGk+X60Wjxs3kLFDMJWge3VICbdbdFiwZpaJ0j+EQvvLF2NrKa7UDLjVobhXiRPh/x4kFwTWnilLOyYuROl7mKOz1mpGmScyZDC+nQnkVyAn+kzezy7k=
conda_forge_output_validation: false
